site:
  title: Redpanda Docs Extensions and Macros
  start_page: preview:ROOT:test.adoc
  url: https://docs-extensions-and-macros.netlify.app
urls:
  html_extension_style: indexify
content:
  sources:
  - url: .
    branches: HEAD
    start_paths: [preview/extensions-and-macros, preview/shared]
ui:
  bundle:
    url: https://github.com/redpanda-data/docs-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
  extensions:
  - './macros/glossary'
  - './macros/config-ref'
  - './macros/helm-ref'
antora:
  extensions:
  - require: './extensions/add-global-attributes'
  - './extensions/version-fetcher/set-latest-version'
  - './extensions/algolia-indexer/index'
  - require: './extensions/unlisted-pages'
  - require: './extensions/replace-attributes-in-attachments'
  - require: './extensions/aggregate-terms'

