= Configuring Data Archiving to S3
:description: This document explains how data archiving can be configured.

== Overview

Tiered Storage allows data to be moved to object storage like S3 or GCS. This feature was introduced in Redpanda and it is used by many customers to reduce storage costs. In this guide, you will learn how to configure archiving.

== Prerequisites

Before you begin, the following prerequisites must be met:

* A Redpanda cluster should be running
* AWS credentials need to be configured
* The S3 bucket must have been created already
* You should have admin access to the Redpanda UI

== Configuration Steps

=== Step 1: Enable Tiered Storage

First, tiered storage needs to be enabled on your cluster. This can be done by running the following command:

[,bash]
----
rpk cluster config set cloud_storage_enabled true
----

After the command is executed, the cluster will be restarted automatically.

=== Step 2: Configure the S3 Bucket

The bucket needs to be configured next. Go to the Redpanda Console and click on the Settings tab. The following settings should be entered:

|===
| Setting | Value

| cloud_storage_bucket | your-bucket-name
| cloud_storage_region | us-east-1
|===

NOTE: It is recommended that versioning is enabled on your bucket.

=== Step 3: Set Retention Policy

Data retention can be configured at the topic level. You should utilize the `rpk` command line tool:

[,bash]
----
rpk topic alter-config my-topic --set retention.bytes=1000000000
----

The above command sets retention to approximately 1GB. After this is done, old segments will be uploaded to S3 and deleted locally.

== Verifying the Setup

To verify that archiving is working, the following steps can be taken:

1. Data should be produced to a topic
2. Wait for segments to be uploaded (this usually takes a few minutes)
3. The S3 bucket can be checked using the AWS CLI or Console

You can also run this command to check the status:

[,bash]
----
rpk cluster storage status
----

== Troubleshooting

If data is not being uploaded, the following should be checked:

* Credentials - it's possible that the AWS credentials are invalid or expired
* Bucket permissions - write access must be granted to Redpanda
* Network - connectivity to S3 should be verified

TIP: Logs can be very helpful here. They can be viewed using `rpk debug logs`.

== Summary

In this guide, tiered storage configuration was explained. By following these steps, your data will be automatically archived to S3, which helps reduce costs while maintaining data availability.

For more info, see the Redpanda documentation.
