'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');

const {
  migrateDescriptionsToPartials,
} = require('../../tools/redpanda-connect/migrate-descriptions-to-partials.js');
const { backfillPageDescriptions } = require('../../tools/redpanda-connect/generate-rpcn-connector-docs.js');

let asciidoctor = null;
try {
  asciidoctor = require('@asciidoctor/core')();
} catch (_) {
  try {
    const { createRequire } = require('module');
    asciidoctor = createRequire(require.resolve('@antora/asciidoc-loader'))('@asciidoctor/core')();
  } catch (_) { /* optional */ }
}
const renderTest = asciidoctor ? test : test.skip;

function partial ({ description, body }) {
  return [
    '// This content is autogenerated. Do not edit manually.',
    '',
    '// tag::attrs[]',
    ...(description ? [`:description: ${description}`] : []),
    '// end::attrs[]',
    '',
    '// tag::body[]',
    body,
    '// end::body[]',
    '',
  ].join('\n');
}

describe('migrateDescriptionsToPartials', () => {
  let root, pagesRoot, partialsRoot;

  beforeEach(() => {
    root = fs.mkdtempSync(path.join(os.tmpdir(), 'migrate-desc-'));
    pagesRoot = path.join(root, 'pages');
    partialsRoot = path.join(root, 'partials', 'descriptions');
  });

  afterEach(() => fs.rmSync(root, { recursive: true, force: true }));

  function writePage (typeDir, name, lines) {
    const dir = path.join(pagesRoot, typeDir);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, `${name}.adoc`), lines.join('\n'), 'utf8');
  }

  function writePartial (typeDir, name, content) {
    const dir = path.join(partialsRoot, typeDir);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, `${name}.adoc`), content, 'utf8');
  }

  function readPage (typeDir, name) {
    return fs.readFileSync(path.join(pagesRoot, typeDir, `${name}.adoc`), 'utf8');
  }

  function run (opts = {}) {
    const logSpy = jest.spyOn(console, 'log').mockImplementation(() => {});
    try {
      return migrateDescriptionsToPartials({ pagesRoot, partialsRoot, ...opts });
    } finally {
      logSpy.mockRestore();
    }
  }

  test('rewires the header attribute and the frozen intro prose onto the partial', () => {
    writePage('outputs', 'sql_raw', [
      '= sql_raw',
      '// tag::single-source[]',
      ':type: output',
      '// tag::meta[]',
      ':description: Executes a query.',
      '// end::meta[]',
      '',
      'component_type_dropdown::[]',
      '',
      'Executes a query.',
      '',
      'include::connect:components:partial$fields/outputs/sql_raw.adoc[]',
      '// end::single-source[]',
      '',
    ]);
    writePartial('outputs', 'sql_raw', partial({
      description: 'Executes a query.',
      body: 'Executes a query.',
    }));

    const dry = run();
    expect(dry.headers).toEqual(['outputs/sql_raw']);
    expect(dry.bodies).toEqual(['outputs/sql_raw']);
    // A dry run must not touch the page.
    expect(readPage('outputs', 'sql_raw')).toContain(':description: Executes a query.');

    const applied = run({ write: true });
    expect(applied.headers).toEqual(['outputs/sql_raw']);
    expect(applied.bodies).toEqual(['outputs/sql_raw']);

    const page = readPage('outputs', 'sql_raw');
    expect(page).toContain('include::connect:components:partial$descriptions/outputs/sql_raw.adoc[tag=attrs]');
    expect(page).toContain('include::connect:components:partial$descriptions/outputs/sql_raw.adoc[tag=body]');
    // The frozen copies are gone, so the page cannot drift from the source.
    expect(page).not.toContain(':description: Executes a query.');
    expect(page.match(/Executes a query\./g)).toBeNull();
    // The attrs include stays inside the meta tag region so single-source
    // stubs keep inheriting :description: as a header attribute.
    const lines = page.split('\n');
    const at = lines.findIndex((l) => l.includes('tag=attrs'));
    expect(lines[at - 1]).toBe('// tag::meta[]');
    expect(lines[at + 1]).toBe('// end::meta[]');
    // Everything below the intro survives.
    expect(page).toContain('include::connect:components:partial$fields/outputs/sql_raw.adoc[]');

    // Idempotent.
    expect(run({ write: true }).headers).toEqual([]);
  });

  test('refuses the body rewire when the page intro carries prose the partial does not', () => {
    writePage('processors', 'branch', [
      '= branch',
      '// tag::meta[]',
      ':description: Creates a branch.',
      '// end::meta[]',
      '',
      'component_type_dropdown::[]',
      '',
      'Creates a branch.',
      '',
      'A hand-written paragraph a docs author added, which the generator has never seen.',
      '',
      '== Error handling',
      '',
      'Details.',
      '',
    ]);
    writePartial('processors', 'branch', partial({
      description: 'Creates a branch.',
      body: 'Creates a branch.',
    }));

    const result = run({ write: true });
    // The header is safe and still migrates...
    expect(result.headers).toEqual(['processors/branch']);
    // ...but the prose stays put rather than being silently deleted.
    expect(result.bodies).toEqual([]);
    expect(result.skipped).toEqual(expect.arrayContaining([
      { page: 'processors/branch', reason: 'intro prose is not reproduced by the partial (needs a human)' },
    ]));
    const page = readPage('processors', 'branch');
    expect(page).toContain('A hand-written paragraph a docs author added');
    expect(page).not.toContain('tag=body');
  });

  test('refuses the body rewire when the description continues past the config listing', () => {
    // Live shape: caches/redpanda splits its description around the generated
    // config tabs. Replacing the intro alone leaves the include and the
    // surviving half both rendering the same prose, which an Antora build
    // showed as the same xref reported twice.
    writePage('caches', 'redpanda', [
      '= redpanda',
      '// tag::meta[]',
      ':description: A Kafka cache.',
      '// end::meta[]',
      '',
      'component_type_dropdown::[]',
      '',
      'A Kafka cache implemented using the Franz client.',
      '',
      '[tabs]',
      '======',
      'Common::',
      '======',
      '',
      'A cache that stores data in a Kafka topic.',
      '',
    ]);
    writePartial('caches', 'redpanda', partial({
      description: 'A Kafka cache.',
      body: 'A Kafka cache implemented using the Franz client.\n\nA cache that stores data in a Kafka topic.',
    }));

    const result = run({ write: true });
    expect(result.headers).toEqual(['caches/redpanda']);
    expect(result.bodies).toEqual([]);
    expect(result.skipped).toEqual(expect.arrayContaining([
      { page: 'caches/redpanda', reason: 'description prose continues past the config listing (needs a human)' },
    ]));
    const page = readPage('caches', 'redpanda');
    expect(page).not.toContain('tag=body');
    // Exactly one copy of each paragraph, as published today.
    expect(page.match(/A cache that stores data in a Kafka topic\./g)).toHaveLength(1);
    expect(page.match(/A Kafka cache implemented using the Franz client\./g)).toHaveLength(1);
  });

  test('leaves a hand-authored meta description alone', () => {
    writePage('outputs', 'drop', [
      '= drop',
      '// tag::meta[]',
      ':description: Drop output reference for silently discarding messages in Redpanda Connect pipelines.',
      '// end::meta[]',
      '',
      'component_type_dropdown::[]',
      '',
      'Drops all messages.',
      '',
    ]);
    writePartial('outputs', 'drop', partial({
      description: 'Drops all messages.',
      body: 'Drops all messages.',
    }));

    const result = run({ write: true });
    expect(result.headers).toEqual([]);
    expect(result.skipped).toEqual(expect.arrayContaining([
      { page: 'outputs/drop', reason: 'hand-authored :description: differs from the summary (needs a human)' },
    ]));
    expect(readPage('outputs', 'drop'))
      .toContain(':description: Drop output reference for silently discarding messages');
  });

  test('a header value that differs only by markup still migrates', () => {
    // The page value and the summary say the same thing; the page just has
    // the link macro the flattener removes. No editorial work to lose.
    writePage('caches', 'redpanda2', [
      '= redpanda2',
      '// tag::meta[]',
      ':description: A cache using the https://github.com/twmb/franz-go[Franz client^].',
      '// end::meta[]',
      '',
      'component_type_dropdown::[]',
      '',
      'Body.',
      '',
    ]);
    writePartial('caches', 'redpanda2', partial({
      description: 'A cache using the Franz client.',
      body: 'Body.',
    }));
    expect(run({ write: true }).headers).toEqual(['caches/redpanda2']);
  });

  test('resolves the rate_limits pages directory to the rate_limits partial', () => {
    writePage('rate_limits', 'local', [
      '= local',
      '// tag::meta[]',
      ':description: A simple rate limit.',
      '// end::meta[]',
      '',
      'component_type_dropdown::[]',
      '',
      'A simple rate limit.',
      '',
    ]);
    writePartial('rate_limits', 'local', partial({
      description: 'A simple rate limit.',
      body: 'A simple rate limit.',
    }));

    const result = run({ write: true });
    expect(result.headers).toEqual(['rate_limits/local']);
    expect(readPage('rate_limits', 'local'))
      .toContain('partial$descriptions/rate_limits/local.adoc[tag=attrs]');
  });

  test('skips a page whose partial was blanked upstream', () => {
    writePage('inputs', 'gone', [
      '= gone',
      '// tag::meta[]',
      ':description: Reads things.',
      '// end::meta[]',
      '',
      'component_type_dropdown::[]',
      '',
      'Reads things.',
      '',
    ]);
    writePartial('inputs', 'gone', [
      '// This content is autogenerated. Do not edit manually. intentionally empty',
      '',
      '// tag::attrs[]',
      '// end::attrs[]',
      '',
      '// tag::body[]',
      '// end::body[]',
      '',
    ].join('\n'));

    const result = run({ write: true });
    expect(result.headers).toEqual([]);
    expect(result.bodies).toEqual([]);
    expect(result.skipped).toEqual(expect.arrayContaining([
      { page: 'inputs/gone', reason: 'description partial is empty' },
    ]));
    expect(readPage('inputs', 'gone')).toContain(':description: Reads things.');
  });

  test('drops a duplicate header :description: the include would otherwise lose to', () => {
    // A blank line inside the header hid the existing attribute from the
    // page-header backfill, so the page ended up with two. AsciiDoc takes the
    // last assignment, so leaving the literal one makes the include a no-op.
    writePage('tracers', 'otel', [
      '= otel',
      ':type: tracer',
      '',
      ':categories: []',
      ':description: Send tracing events to a collector.',
      '',
      'component_type_dropdown::[]',
      '',
      'Send tracing events to a collector.',
      '',
    ]);
    writePartial('tracers', 'otel', partial({
      description: 'Send tracing events to a collector.',
      body: 'Send tracing events to a collector.',
    }));

    run({ write: true });
    const page = readPage('tracers', 'otel');
    expect(page).toContain('partial$descriptions/tracers/otel.adoc[tag=attrs]');
    expect(page.split('\n').filter((l) => l.startsWith(':description:'))).toEqual([]);
  });

  test('--skip-body rewires headers only', () => {
    writePage('outputs', 'sql_raw', [
      '= sql_raw',
      '// tag::meta[]',
      ':description: Executes a query.',
      '// end::meta[]',
      '',
      'component_type_dropdown::[]',
      '',
      'Executes a query.',
      '',
    ]);
    writePartial('outputs', 'sql_raw', partial({
      description: 'Executes a query.',
      body: 'Executes a query.',
    }));

    const result = run({ write: true, skipBody: true });
    expect(result.headers).toEqual(['outputs/sql_raw']);
    expect(result.bodies).toEqual([]);
    expect(readPage('outputs', 'sql_raw')).not.toContain('tag=body');
  });

  test('the page-header backfill leaves a migrated page alone', () => {
    // #246's backfill guards on a literal :description:. Without an arm for
    // the attrs include it splices a competing meta block into every migrated
    // page, so the page carries a dead include plus a hand-inserted attribute.
    writePage('outputs', 'sql_raw', [
      '= sql_raw',
      '// tag::single-source[]',
      ':type: output',
      '// tag::meta[]',
      'include::connect:components:partial$descriptions/outputs/sql_raw.adoc[tag=attrs]',
      '// end::meta[]',
      '',
      'Body.',
      '',
    ]);
    const result = backfillPageDescriptions(
      { outputs: [{ name: 'sql_raw', summary: 'Executes a query.' }] },
      { pagesRoot }
    );
    expect(result.backfilled).toEqual([]);
    const page = readPage('outputs', 'sql_raw');
    expect(page).not.toContain(':description: Executes a query.');
    expect(page.match(/tag::meta\[\]/g)).toHaveLength(1);
  });

  renderTest('a migrated page resolves both tags and publishes the flattened description', () => {
    writePage('processors', 'branch', [
      '= branch',
      '// tag::meta[]',
      ':description: The branch processor creates a request via a xref:guides:bloblang/about.adoc[Bloblang mapping].',
      '// end::meta[]',
      '',
      'component_type_dropdown::[]',
      '',
      'The `branch` processor creates a request via a xref:guides:bloblang/about.adoc[Bloblang mapping].',
      '',
    ]);
    writePartial('processors', 'branch', partial({
      description: 'The branch processor creates a request via a Bloblang mapping.',
      body: 'The `branch` processor creates a request via a xref:guides:bloblang/about.adoc[Bloblang mapping].',
    }));
    run({ write: true });

    // Resolve the Antora partial$ target to a local path so Asciidoctor alone
    // can load it (the full cross-component resolution is covered by the real
    // Antora build in the PR description).
    const pagePath = path.join(pagesRoot, 'processors', 'branch.adoc');
    fs.writeFileSync(pagePath, fs.readFileSync(pagePath, 'utf8').replace(
      /include::connect:components:partial\$descriptions\/processors\/branch\.adoc/g,
      `include::${path.join(partialsRoot, 'processors', 'branch.adoc')}`
    ), 'utf8');

    const mem = asciidoctor.MemoryLogger.create();
    asciidoctor.LoggerManager.setLogger(mem);
    const doc = asciidoctor.loadFile(pagePath, { safe: 'unsafe' });
    const html = doc.convert();
    expect(mem.getMessages().map((m) => m.getText())).toEqual([]);
    // The meta description is plain text, not raw macro markup.
    expect(doc.getAttribute('description'))
      .toBe('The branch processor creates a request via a Bloblang mapping.');
    // The body still renders the xref as a link, not as literal text.
    expect(html).toContain('Bloblang mapping');
    expect(html).not.toContain('xref:guides:bloblang/about.adoc');
  });
});
