'use strict';

const path = require('path');
const fs = require('fs');

const {
  migrateMetadataToPartials,
  isEmptyMetadataPartial,
} = require('../../tools/redpanda-connect/migrate-metadata-to-partials.js');

const BANNER = '// This content is autogenerated. Do not edit manually.';

describe('migrate-metadata: isEmptyMetadataPartial', () => {
  test('true for a banner-only / no-metadata partial', () => {
    expect(isEmptyMetadataPartial(`${BANNER}\n\nThe description no longer contains a == Metadata section.\n`)).toBe(true);
    expect(isEmptyMetadataPartial(`${BANNER}\n`)).toBe(true);
    expect(isEmptyMetadataPartial('')).toBe(true);
  });

  test('false when the partial contains a real == Metadata section', () => {
    expect(isEmptyMetadataPartial(`${BANNER}\n\n== Metadata\n\n- \`foo\`: bar\n`)).toBe(false);
  });
});

describe('migrate-metadata: does not migrate when the generated partial is empty', () => {
  const tmp = path.join(__dirname, 'tmp-migrate-empty');
  let cwd;

  const pageRel = 'modules/components/pages/inputs/thing.adoc';
  const partialRel = 'modules/components/partials/metadata/inputs/thing.adoc';
  const PAGE = [
    '= thing',
    '// tag::single-source[]',
    ':type: input',
    '',
    'Does a thing.',
    '',
    '== Metadata',
    '',
    'This input adds the following metadata fields to each message:',
    '',
    '- `thing_id`: The id.',
    '',
    'include::connect:components:partial$fields/inputs/thing.adoc[]',
    '',
    '// end::single-source[]',
    '',
  ].join('\n');

  beforeAll(() => {
    if (fs.existsSync(tmp)) fs.rmSync(tmp, { recursive: true, force: true });
    fs.mkdirSync(path.join(tmp, path.dirname(pageRel)), { recursive: true });
    fs.mkdirSync(path.join(tmp, path.dirname(partialRel)), { recursive: true });
    fs.writeFileSync(path.join(tmp, pageRel), PAGE);
    // An EMPTY generated partial already exists (no == Metadata section).
    fs.writeFileSync(path.join(tmp, partialRel), `${BANNER}\n\nThe description no longer contains a == Metadata section.\n`);
    cwd = process.cwd();
    process.chdir(tmp);
  });

  afterAll(() => {
    process.chdir(cwd);
    fs.rmSync(tmp, { recursive: true, force: true });
  });

  test('leaves the page inline metadata intact', () => {
    migrateMetadataToPartials({ write: true });
    const page = fs.readFileSync(path.join(tmp, pageRel), 'utf8');
    // Inline metadata preserved; NOT replaced by an include to the empty partial.
    expect(page).toContain('- `thing_id`: The id.');
    expect(page).not.toContain('partial$metadata/inputs/thing.adoc');
  });
});
