= Extensions and Macros Preview
:page-categories: some-invalid-category

This page is a preview of extensions and macros.

== Terms

Terms must be defined in the `terms` module of the `shared` component (`shared/modules/terms/partials`).

Each partial file in this module is a term. Each file must include the following attributes:

- `term-name`: The name of the term.
- `hover-text`: A short definition of the term to be used as hover-over text.

If a page called `reference:glossary.adoc` exists in your component version, the contents of each term file gets merged into glossary during the build. Terms are merged in alphabetical order, according to the filename. The `aggregate-terms` extension is responsible for merging the content of each file into the glossary.

To reference a term in a doc topic, use the following syntax:

[,asciidoc]
----
glossterm:<term-name>[]
----

Replace `<term-name>` with the value of the `term-name` attribute in a term file.

To add custom link text for a term, which can be useful for displaying plurals or context-specific variations of the term without changing the term reference, use this syntax:

[,asciidoc]
----
glossterm:<term-name>[,<custom-link-text>]
----

Here, replace `<custom-link-text>` with your text that will appear as the link. For example:

glossterm:test term[,This link text is custom.]

The `hover-text` attribute is read from the term file and used to add hover text to the term.

The rules for whether a link to the glossary entry is added to the term, depend on what content is available on the term page:

- If you include only a title and the required `term-name` and `hover-text` attributes, a link to the glossary entry is added to the term.
+
For example: glossterm:hover-only term[]
- If you include other Asciidoc content in the term page, such as headings, images, or paragraphs, a link to the glossary entry is added to the term so that users can read the full definition.
+
For example: glossterm:test term[]
- If you include an external URL in the `link` attribute, a link to that URL is added to the term.
+
For example: glossterm:external term[]

=== Local development

For local development, you can test what your hover text will look like by adding the description to the macro like so:

[,asciidoc]
----
glossterm:term[This description is located in the Asciidoc source of this page]
----

This glossterm:term[This description is located in the Asciidoc source of this page] is defined inline on this page. Inline terms do not include an internal link to the glossary page.

== config_ref

config_ref:test,true,cluster-properties[]

config_ref:test,false[]

== helm_ref

helm_ref:storage[]

== Latest versions

The `version fetcher` extension gets the latest version of Redpanda and Redpanda Console and assigns them to the following attributes:

- `\{full-version}`: {full-version}
- `\{latest-redpanda-version}`: {latest-redpanda-version}
- `\{redpanda-beta-version}`: {redpanda-beta-version}
- `\{redpanda-beta-tag}`: {redpanda-beta-tag}
- `\{latest-release-commit}`: {latest-release-commit}
- `\{latest-console-version}`: {latest-console-version}
- `\{console-beta-version}`: {console-beta-version}
- `\{console-beta-tag}`: {console-beta-tag}
- `\{latest-operator-version}`: {latest-operator-version}
- `\{latest-redpanda-helm-chart-version}`: {latest-redpanda-helm-chart-version}

== Attachments

By default, Antora does not replace attributes in attachment files. Download this test attachment to make sure that the correct elements were replaced:

xref:preview:ROOT:attachment$test.yaml[Download attachment]

The archive attachments extension is configured to archive all YAML files for the `preview` component. Test the extension by downloading this archive. It should contain the `test.yaml` file and include all replacements made by the replace-attributes-in-attachments extension.

link:/test.tar.gz[Download archive]

== Bloblang samples

[,json,subs="attributes+"]
----
{page-bloblang-samples}
----

== End-of-life attributes

This section provides a test for the compute-end-of-life extension as an example of what it generates.

The `preview` component is configured with a release date of {page-release-date}. The extension then generates the following data for the UI to use to build and display a notification banner for EoL versions:

- `\{page-is-nearing-eol}`: {page-is-nearing-eol}
- `\{page-is-past-eol}`: {page-is-past-eol}
- `\{page-eol-date}`: {page-eol-date}
- `\{page-eol-doc}`: {page-eol-doc}
- `\{page-upgrade-doc}`: {page-upgrade-doc}

== Code highlights

[source,js,lines=1-3+5+6]
----
function helloWorld() {
    console.log("Hello, World!") <sample>;
    console.log("This is a sample.");
    console.log("With multiple lines.");
    console.log("Highlighted using Prism.");
}
----

== Connector table with all data

component_table::[all]