= nats_kv
// tag::single-source[]
:type: processor
:status: beta
:categories: ["Services"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Perform operations on a NATS key-value bucket.

ifndef::env-cloud[]
Introduced in version 4.12.0.
endif::[]

[tabs]
======
Common::
+
--

```yml
# Common configuration fields, showing default values
label: ""
nats_kv:
  urls: [] # No default (required)
  bucket: my_kv_bucket # No default (required)
  operation: "" # No default (required)
  key: foo # No default (required)
```

--
Advanced::
+
--

```yml
# All configuration fields, showing default values
label: ""
nats_kv:
  urls: [] # No default (required)
  bucket: my_kv_bucket # No default (required)
  operation: "" # No default (required)
  key: foo # No default (required)
  revision: "42" # No default (optional)
  timeout: 5s
  tls:
    enabled: false
    skip_cert_verify: false
    enable_renegotiation: false
    root_cas: ""
    root_cas_file: ""
    client_certs: []
  auth:
    nkey_file: ./seed.nk # No default (optional)
    nkey: "" # No default (optional)
    user_credentials_file: ./user.creds # No default (optional)
    user_jwt: "" # No default (optional)
    user_nkey_seed: "" # No default (optional)
```

--
======

== KV operations

The NATS KV processor supports many KV operations using the <<operation>> field. Along with `get`, `put`, and `delete`, this processor supports atomic operations like `update` and `create`, as well as utility operations like `purge`, `history`, and `keys`.

== Metadata

This processor adds the following metadata fields to each message, depending on the chosen `operation`:

=== get, get_revision
``` text
- nats_kv_key
- nats_kv_bucket
- nats_kv_revision
- nats_kv_delta
- nats_kv_operation
- nats_kv_created
```

=== create, update, delete, purge

``` text
- nats_kv_key
- nats_kv_bucket
- nats_kv_revision
- nats_kv_operation
```

=== keys
``` text
- nats_kv_bucket
```

include::components:partial$nats_intro.adoc[]

== Fields

=== `urls`

A list of URLs to connect to. If a list item contains commas, it will be expanded into multiple URLs.


*Type*: `array`


```yml
# Examples

urls:
  - nats://127.0.0.1:4222

urls:
  - nats://username:password@127.0.0.1:4222
```

=== `bucket`

The name of the KV bucket.


*Type*: `string`


```yml
# Examples

bucket: my_kv_bucket
```

=== `operation`

The operation to perform on the KV bucket.


*Type*: `string`


|===
| Option | Summary

| `create`
| Adds the key/value pair if it does not exist. Returns an error if it already exists.
| `delete`
| Deletes the key/value pair, but keeps historical values.
| `get`
| Returns the latest value for `key`.
| `get_revision`
| Returns the value of `key` for the specified `revision`.
| `history`
| Returns historical values of `key` as an array of objects containing the following fields: `key`, `value`, `bucket`, `revision`, `delta`, `operation`, `created`.
| `keys`
| Returns the keys in the `bucket` which match the `keys_filter` as an array of strings.
| `purge`
| Deletes the key/value pair and all historical values.
| `put`
| Places a new value for the key into the store.
| `update`
| Updates the value for `key` only if the `revision` matches the latest revision.

|===

=== `key`

The key for each message. Supports https://docs.nats.io/nats-concepts/subjects#wildcards[wildcards^] for the `history` and `keys` operations.
This field supports xref:configuration:interpolation.adoc#bloblang-queries[interpolation functions].


*Type*: `string`


```yml
# Examples

key: foo

key: foo.bar.baz

key: foo.*

key: foo.>

key: foo.${! json("meta.type") }
```

=== `revision`

The revision of the key to operate on. Used for `get_revision` and `update` operations.
This field supports xref:configuration:interpolation.adoc#bloblang-queries[interpolation functions].


*Type*: `string`


```yml
# Examples

revision: "42"

revision: ${! @nats_kv_revision }
```

=== `timeout`

The maximum period to wait on an operation before aborting and returning an error.


*Type*: `string`

*Default*: `"5s"`

=== `tls`

Custom TLS settings can be used to override system defaults.


*Type*: `object`


=== `tls.enabled`

Whether custom TLS settings are enabled.


*Type*: `bool`

*Default*: `false`

=== `tls.skip_cert_verify`

Whether to skip server side certificate verification.


*Type*: `bool`

*Default*: `false`

=== `tls.enable_renegotiation`

Whether to allow the remote server to repeatedly request renegotiation. Enable this option if you're seeing the error message `local error: tls: no renegotiation`.


*Type*: `bool`

*Default*: `false`

ifndef::env-cloud[]
Requires version 3.45.0 or newer
endif::[]

=== `tls.root_cas`

An optional root certificate authority to use. This is a string, representing a certificate chain from the parent trusted root certificate, to possible intermediate signing certificates, to the host certificate.

include::components:partial$secret_warning.adoc[]



*Type*: `string`

*Default*: `""`

```yml
# Examples

root_cas: |-
  -----BEGIN CERTIFICATE-----
  ...
  -----END CERTIFICATE-----
```

=== `tls.root_cas_file`

An optional path of a root certificate authority file to use. This is a file, often with a .pem extension, containing a certificate chain from the parent trusted root certificate, to possible intermediate signing certificates, to the host certificate.


*Type*: `string`

*Default*: `""`

```yml
# Examples

root_cas_file: ./root_cas.pem
```

=== `tls.client_certs`

A list of client certificates to use. For each certificate either the fields `cert` and `key`, or `cert_file` and `key_file` should be specified, but not both.


*Type*: `array`

*Default*: `[]`

```yml
# Examples

client_certs:
  - cert: foo
    key: bar

client_certs:
  - cert_file: ./example.pem
    key_file: ./example.key
```

=== `tls.client_certs[].cert`

A plain text certificate to use.


*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].key`

A plain text certificate key to use.

include::components:partial$secret_warning.adoc[]



*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].cert_file`

The path of a certificate to use.


*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].key_file`

The path of a certificate key to use.


*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].password`

A plain text password for when the private key is password encrypted in PKCS#1 or PKCS#8 format. The obsolete `pbeWithMD5AndDES-CBC` algorithm is not supported for the PKCS#8 format.

Because the obsolete pbeWithMD5AndDES-CBC algorithm does not authenticate the ciphertext, it is vulnerable to padding oracle attacks that can let an attacker recover the plaintext.

include::components:partial$secret_warning.adoc[]



*Type*: `string`

*Default*: `""`

```yml
# Examples

password: foo

password: ${KEY_PASSWORD}
```

=== `auth`

Optional configuration of NATS authentication parameters.


*Type*: `object`


=== `auth.nkey_file`

An optional file containing a NKey seed.


*Type*: `string`


```yml
# Examples

nkey_file: ./seed.nk
```

=== `auth.nkey`

Your NKey seed or private key.

include::components:partial$secret_warning.adoc[]

*Type*: `string`

ifndef::env-cloud[]
Requires version 3.48.0 or newer
endif::[]

```yml
# Examples

nkey: UDXU4RCSJNZOIQHZNWXHXORDPRTGNJAHAHFRGZNEEJCPQTT2M7NLCNF4
```

=== `auth.user_credentials_file`

An optional file containing user credentials which consist of a user JWT and corresponding NKey seed.


*Type*: `string`


```yml
# Examples

user_credentials_file: ./user.creds
```

=== `auth.user_jwt`

An optional plain text user JWT to use along with the corresponding user NKey seed.

include::components:partial$secret_warning.adoc[]



*Type*: `string`


=== `auth.user_nkey_seed`

An optional plain text user NKey seed to use along with the corresponding user JWT.

include::components:partial$secret_warning.adoc[]



*Type*: `string`

// end::single-source[]