= openai_embeddings
// tag::single-source[]
:type: processor
:page-beta: true
:categories: ["AI"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Generates vector embeddings to represent input text, using the OpenAI API.

ifndef::env-cloud[]
Introduced in version 4.32.0.
endif::[]

```yml
# Config fields, showing default values
label: ""
openai_embeddings:
  server_address: https://api.openai.com/v1
  api_key: "" # No default (required)
  model: text-embedding-3-large # No default (required)
  text_mapping: "" # No default (optional)
```

This processor sends text strings to the OpenAI API, which generates vector embeddings. By default, the processor submits the entire payload of each message as a string, unless you use the `text_mapping` configuration field to customize it.

To learn more about vector embeddings, see the https://platform.openai.com/docs/guides/embeddings[OpenAI API documentation^].

== Fields

=== `server_address`

The Open API endpoint that the processor sends requests to. Update the default value to use another OpenAI compatible service.


*Type*: `string`

*Default*: `"https://api.openai.com/v1"`

=== `api_key`

The API key for OpenAI API.

include::components:partial$secret_warning.adoc[]



*Type*: `string`


=== `model`

The name of the OpenAI model to use.


*Type*: `string`


```yml
# Examples

model: text-embedding-3-large

model: text-embedding-3-small

model: text-embedding-ada-002
```

=== `text_mapping`

The text you want to generate a vector embedding for. By default, the processor submits the entire payload as a string.


*Type*: `string`

// end::single-source[]