= sync_response
// tag::single-source[]
:type: processor
:status: stable
:categories: ["Utility"]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Adds the payload in its current state as a synchronous response to the input source, where it is dealt with according to that specific input type.

```yml
# Config fields, showing default values
label: ""
sync_response: {}
```

ifndef::env-cloud[]
For most inputs this mechanism is ignored entirely, in which case the sync response is dropped without penalty. It is therefore safe to use this processor even when combining input types that might not have support for sync responses. An example of an input able to utilize this is the `http_server`.

For more information please read xref:guides:sync_responses.adoc[synchronous responses].
endif::[]
ifdef::env-cloud[]
For most inputs this mechanism is ignored entirely, in which case the sync response is dropped without penalty. It is therefore safe to use this processor even when combining input types that might not have support for sync responses.
endif::[]

// end::single-source[]