{{- define "gvList" -}}
{{- $groupVersions := . -}}

// Autogenerated documentation. Do not edit this page See https://github.com/redpanda-data/docs/blob/main/.github/workflows/generate-crd.yml.
{{- with index $groupVersions 0 }}
= {{ . }}
{{- end }}
:anchor_prefix: k8s-api
:description: Custom resource definitions for Redpanda resources. Use the Redpanda resources to create and manage Redpanda clusters, users and topics with the Redpanda Operator.
:page-aliases: reference:k-topic-crd.adoc

{{ range $groupVersions }}
{{ template "gvDetails" . }}
{{ end }}

{{- end -}}
