= questdb
:type: output
:page-beta: true
:categories: ["Services"]

// tag::single-source[]

// © 2024 Redpanda Data Inc.


component_type_dropdown::[]


Pushes messages to a https://questdb.io/docs/[QuestDB^] table.

ifndef::env-cloud[]
Introduced in version 4.37.0.
endif::[]

[tabs]
======
Common::
+
--
```yml
# Common configuration fields, showing default values
output:
  label: ""
  questdb:
    max_in_flight: 64
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
    address: localhost:9000 # No default (required)
    username: "" # No default (optional)
    password: "" # No default (optional)
    token: "" # No default (optional)
    table: trades # No default (required)
    designated_timestamp_field: "" # No default (optional)
    designated_timestamp_unit: auto
    timestamp_string_fields: [] # No default (optional)
    timestamp_string_format: Jan _2 15:04:05.000000Z0700
    symbols: [] # No default (optional)
    doubles: [] # No default (optional)
    error_on_empty_messages: false
```
--
Advanced::
+
--
```yml
# All configuration fields, showing default values
output:
  label: ""
  questdb:
    max_in_flight: 64
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
      processors: [] # No default (optional)
    tls:
      enabled: false
      skip_cert_verify: false
      enable_renegotiation: false
      root_cas: ""
      root_cas_file: ""
      client_certs: []
    address: localhost:9000 # No default (required)
    username: "" # No default (optional)
    password: "" # No default (optional)
    token: "" # No default (optional)
    retry_timeout: "" # No default (optional)
    request_timeout: "" # No default (optional)
    request_min_throughput: 0 # No default (optional)
    table: trades # No default (required)
    designated_timestamp_field: "" # No default (optional)
    designated_timestamp_unit: auto
    timestamp_string_fields: [] # No default (optional)
    timestamp_string_format: Jan _2 15:04:05.000000Z0700
    symbols: [] # No default (optional)
    doubles: [] # No default (optional)
    error_on_empty_messages: false
```
--
======

IMPORTANT: Redpanda Data recommends enabling the dedupe feature on the QuestDB server. For more information about deploying, configuring, and using QuestDB, see the https://questdb.io/docs/[QuestDB documentation^]. 

== Performance

For improved performance, this output sends multiple messages in parallel. You can tune the maximum number of in-flight messages (or message batches), using the `max_in_flight` field. 

You can configure batches at both the input and output level. For more information, see xref:configuration:batching.adoc[Message Batching].

== Fields

=== `max_in_flight`

The maximum number of messages to have in flight at a given time. Increase this value to improve throughput.

*Type*: `int`

*Default*: `64`

=== `batching`

Allows you to configure a xref:configuration:batching.adoc[batching policy].

*Type*: `object`

```yml
# Examples
batching:
  byte_size: 5000
  count: 0
  period: 1s
batching:
  count: 10
  period: 1s
batching:
  check: this.contains("END BATCH")
  count: 0
  period: 1m
```
=== `batching.count`

The number of messages after which the batch is flushed. Set to `0` to disable count-based batching.

*Type*: `int`

*Default*: `0`

=== `batching.byte_size`

The amount of bytes at which the batch is flushed. Set to `0` to disable size-based batching.

*Type*: `int`

*Default*: `0`

=== `batching.period`

The period of time after which an incomplete batch is flushed regardless of its size.

*Type*: `string`

*Default*: `""`

```yml
# Examples
period: 1s
period: 1m
period: 500ms
```
=== `batching.check`

A xref:guides:bloblang/about.adoc[Bloblang query] that returns a boolean value indicating whether a message should end a batch.

*Type*: `string`

*Default*: `""`

```yml
# Examples
check: this.type == "end_of_transaction"
```

=== `batching.processors`

For aggregating and archiving message batches, you can add a list of xref:components:processors/about.adoc[processors] to apply to a batch as it is flushed. All resulting messages are flushed as a single batch even when you configure processors to split the batch into smaller batches.

*Type*: `array`

```yml
# Examples
processors:
  - archive:
      format: concatenate
processors:
  - archive:
      format: lines
processors:
  - archive:
      format: json_array
```

=== `tls`

Override system defaults with custom TLS settings.

*Type*: `object`

=== `tls.enabled`

Whether custom TLS settings are enabled.

*Type*: `bool`

*Default*: `false`

=== `tls.skip_cert_verify`

Whether to skip server-side certificate verification.

*Type*: `bool`

*Default*: `false`

=== `tls.enable_renegotiation`

Whether to allow the remote server to request renegotiation. Enable this option if you're seeing the error message `local error: tls: no renegotiation`.

*Type*: `bool`

*Default*: `false`

ifndef::env-cloud[]
Requires version 3.45.0 or newer
endif::[]

=== `tls.root_cas`

Specify a certificate authority to use (optional). This is a string that represents a certificate chain from the parent trusted root certificate, through possible intermediate signing certificates, to the host certificate.

include::components:partial$secret_warning.adoc[]

*Type*: `string`

*Default*: `""`

```yml
# Examples
root_cas: |-
  -----BEGIN CERTIFICATE-----
  ...
  -----END CERTIFICATE-----
```
=== `tls.root_cas_file`

Specify the path to a root certificate authority file (optional). This is a file, often with a `.pem` extension, which contains a certificate chain from the parent trusted root certificate, through possible intermediate signing certificates, to the host certificate.certificate.

*Type*: `string`

*Default*: `""`

```yml
# Examples
root_cas_file: ./root_cas.pem
```
=== `tls.client_certs`

A list of client certificates to use. For each certificate specify values for either the `cert` and `key` fields, or `cert_file` and `key_file` fields.

*Type*: `array`

*Default*: `[]`

```yml
# Examples
client_certs:
  - cert: foo
    key: bar
client_certs:
  - cert_file: ./example.pem
    key_file: ./example.key
```
=== `tls.client_certs[].cert`

The plain text certificate to use.

*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].key`

The plain text certificate key to use.

include::components:partial$secret_warning.adoc[]

*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].cert_file`

The path to the certificate to use.

*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].key_file`

The path of a certificate key to use.

*Type*: `string`

*Default*: `""`

=== `tls.client_certs[].password`

The plain text password for when the private key is password encrypted in PKCS#1 or PKCS#8 format. The obsolete `pbeWithMD5AndDES-CBC` algorithm is not supported for the PKCS#8 format. 

WARNING: The `pbeWithMD5AndDES-CBC` algorithm does not authenticate ciphertext, and is vulnerable to padding oracle attacks which may allow an attacker to recover the plain text password.

include::components:partial$secret_warning.adoc[]

*Type*: `string`

*Default*: `""`

```yml
# Examples
password: foo
password: ${KEY_PASSWORD}
```
=== `address`

The host and port of the QuestDB server.

*Type*: `string`

```yml
# Examples
address: localhost:9000
```
=== `username`

The username to use for basic authentication.

include::components:partial$secret_warning.adoc[]

*Type*: `string`

=== `password`

The password to use for basic authentication.

include::components:partial$secret_warning.adoc[]

*Type*: `string`

=== `token`

The bearer token to use for authentication, which takes precedence over the basic authentication username and password.

include::components:partial$secret_warning.adoc[]

*Type*: `string`

=== `retry_timeout`

The period of time to continue retrying after a failed HTTP request. The interval between retries is an exponential backoff starting at 10 ms, and doubling after each failed attempt up to a maximum of 1 second.

*Type*: `string`

=== `request_timeout`

The period of time to wait for a response from the QuestDB server in addition to any connection timeout calculated for the `request_min_throughput` field.

*Type*: `string`

=== `request_min_throughput`

The minimum expected throughput in bytes per second for HTTP requests. If the throughput is lower than this value, the connection times out. The `quest_db` output uses this value to calculate an additional timeout on top of the `request_timeout`. This setting is useful for large requests. Set it to `0` to disable this logic.

*Type*: `int`

=== `table`

The destination table in QuestDB.

*Type*: `string`

```yml
# Examples
table: trades
```

=== `designated_timestamp_field`

The name of the designated timestamp field in QuestDB.

*Type*: `string`

=== `designated_timestamp_unit`

Units used for the designated timestamp field in QuestDB.

*Type*: `string`

*Default*: `auto`

=== `timestamp_string_fields`

String fields with textual timestamps.

*Type*: `array`

=== `timestamp_string_format`

The timestamp format, which is used when parsing timestamp string fields and uses Golang's time formatting.

*Type*: `string`

*Default*: `Jan _2 15:04:05.000000Z0700`

=== `symbols`

Columns that must be the `symbol` type. String values default to `string` types.

*Type*: `array`

=== `doubles`

Columns that must be the `double` type, with `int` as the default.

*Type*: `array`

=== `error_on_empty_messages`

Mark a message as an error if it is empty after field validation.

*Type*: `bool`

*Default*: `false`

// end::single-source[]